package com.angelee.community.mapper;

import com.angelee.community.entity.DiscussPost;
import com.angelee.community.entity.DiscussPostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DiscussPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    long countByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    int deleteByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    int insert(DiscussPost row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    int insertSelective(DiscussPost row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    List<DiscussPost> selectByExampleWithRowbounds(DiscussPostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    List<DiscussPost> selectByExample(DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    DiscussPost selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    int updateByExampleSelective(@Param("row") DiscussPost row, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    int updateByExample(@Param("row") DiscussPost row, @Param("example") DiscussPostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    int updateByPrimaryKeySelective(DiscussPost row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discuss_post
     *
     * @mbg.generated Sun Aug 06 16:13:27 CST 2023
     */
    int updateByPrimaryKey(DiscussPost row);
}